### ISSUE TITLE
Extent change from initialExtent doesn't trigger canGoToPrevious change

### ISSUE THREAD

**Issue by davetimmins** [davetimmins/arcgis-extentnavigation-widget#1]
Pan works as expected but not zooming in/out. The `canGoToPrevious` property doesn't update and so the UI doesn't correctly reflect the state, although the extent is still stored correctly.

**Comment by ycabon** [comment]
watching `view.stationary` would be better than `view.interacting`. `stationary` is a combo of `!view.interacting` and `!view.animation`.

**Comment by davetimmins** [comment]
Cool, that fixes both issues, only have to watch stationary and not viewpoint too. Storing the viewpoint though as you suggested.
